# Generated by Django 5.0.1 on 2024-02-12 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('live_time', models.IntegerField(default=15)),
                ('referor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_referor', to=settings.AUTH_USER_MODEL)),
                ('referree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_referree', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
