# Generated by Django 5.0.1 on 2024-02-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_huuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HuUser',
        ),
    ]
