# Generated by Django 5.0.1 on 2024-02-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_delete_huuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.IntegerField(default=0),
        ),
    ]
