# Generated by Django 5.0.1 on 2024-02-08 16:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 16, 38, 43, 784648, tzinfo=datetime.timezone.utc), verbose_name='date of registration'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(default=datetime.datetime(2024, 2, 8, 16, 38, 43, 784895, tzinfo=datetime.timezone.utc), verbose_name='date of creation')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
        ),
    ]
