# Generated by Django 5.0.1 on 2024-02-08 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_remove_user_token_user_date_registration_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 16, 40, 56, 868803, tzinfo=datetime.timezone.utc), verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 16, 40, 56, 868481, tzinfo=datetime.timezone.utc), verbose_name='date of registration'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='None', max_length=254, unique=True),
        ),
    ]
