# Generated by Django 5.0.1 on 2024-02-08 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_alter_token_date_creation_alter_token_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of creation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date of registration'),
        ),
    ]
