# Generated by Django 5.0.1 on 2024-02-09 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_token_date_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='owner',
        ),
        migrations.AddField(
            model_name='token',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tokens', to='authapp.user'),
        ),
        migrations.AddField(
            model_name='token',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal_tokens', to='authapp.user'),
        ),
    ]
