# Generated by Django 5.0.1 on 2024-02-09 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_remove_token_owner_token_referee_token_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='referee',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_tokens', to='authapp.user'),
        ),
    ]
