# Generated by Django 5.0.1 on 2024-02-09 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_alter_token_referee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='referee',
        ),
        migrations.AlterField(
            model_name='token',
            name='referrer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='authapp.user'),
        ),
    ]
