# Generated by Django 5.0.1 on 2024-02-09 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_remove_token_referee_alter_token_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='referrer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='authapp.user'),
        ),
    ]
