# Generated by Django 5.0.1 on 2024-02-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_token_referee'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='token_status',
            field=models.BooleanField(default=True),
        ),
    ]
