# Generated by Django 5.0.1 on 2024-02-09 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_token_token_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='referee',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referee_user', to='authapp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='xxx@yyy.zzz', max_length=254, unique=True, verbose_name='Input yor e-mail'),
        ),
    ]
